name: Build and Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 14.x

      - name: yarn install and build
        run: |
          yarn
          yarn build
        env:
          CI: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: website
          path: dist

  deploy:
    needs: [build]
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: website

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: website
